--generated by datagrip's data extractor and sql generator
drop table if exists olympic_cities;

create table olympic_cities
(
    id             bigint not null
        primary key,
    geom           geometry(Point, 4326),
    year         varchar,
    city         varchar,
    country      varchar,
    times_hosted varchar
);

alter table olympic_cities
    owner to postgres;

INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (4, '0101000020E6100000643BDF4F8DB73740B29DEFA7C6FB4240', '1896 & 2004 Summer Olympics', 'Athens', 'Greece', '2');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (27, '0101000020E6100000022B8716D9CE024004560E2DB26D4840', '1900 & 1924 Summer Olympics', 'Paris', 'France', '2');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (37, '0101000020E6100000E9263108AC8C56C0C74B378941504340', '1904 Summer Olympics', 'St. Louis', 'United States', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (18, '0101000020E6100000B0726891ED7CBFBF37894160E5C04940', '1908 & 1948 & 2012  Summer Olympics', 'London', 'England', '3');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (39, '0101000020E6100000C520B07268113240273108AC1CAA4D40', '1912  Summer Olympics', 'Stockholm', 'Sweden', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (3, '0101000020E61000009A99999999991140B29DEFA7C69B4940', '1920  Summer Olympics', 'Antwerp', 'Belgium', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (2, '0101000020E61000009A99999999991340E5D022DBF92E4A40', '1928  Summer Olympics', 'Amsterdam', 'Netherlands', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (19, '0101000020E61000000000000000905DC06666666666064140', '1932 & 1984 Summer Olympics', 'Los Angeles', 'United States', '2');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (8, '0101000020E61000006ABC749318C42A401904560E2D424A40', '1936 Summer Olympics', 'Berlin', 'Germany', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (14, '0101000020E6100000E3A59BC420F03840D9CEF753E3154E40', '1952 Summer Olympics', 'Helsinki', 'Finland', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (20, '0101000020E6100000894160E5D01E6240D578E92631E842C0', '1956 Summer Olympics', 'Melbourne', 'Australia', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (30, '0101000020E610000000000000000029403333333333F34440', '1960 Summer Olympics', 'Rome', 'Italy', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (41, '0101000020E610000060E5D022DB7561408195438B6CD74140', '1964 & 2020 Summer Olympics', 'Tokyo', 'Japan', '2');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (21, '0101000020E61000008D976E1283C858C0022B8716D96E3340', '1968 Summer Olympics', 'Mexico City', 'Mexico', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (24, '0101000020E6100000FCA9F1D24D2227401B2FDD2406114840', '1972 Summer Olympics', 'Munich', 'West Germany', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (22, '0101000020E61000003F355EBA496452C0C74B378941C04640', '1976 Summer Olympics', 'Montreal', 'Canada', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (23, '0101000020E61000001F85EB51B8CE42400000000000E04B40', '1980 Summer Olympics', 'Moscow', 'USSR', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (34, '0101000020E6100000D9CEF753E3BD5F407F6ABC7493C84240', '1988 Summer Olympics', 'Seoul', 'South Korea', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (6, '0101000020E6100000105839B4C87601401B2FDD2406B14440', '1992 Summer Olympics', 'Barcelona', 'Spain', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (5, '0101000020E6100000295C8FC2F51855C0713D0AD7A3E04040', '1996 Summer Olympics', 'Atlanta', 'United States', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (40, '0101000020E61000001F85EB51B8E662401F85EB51B8EE40C0', '2000 Summer Olympics', 'Sydney', 'Australia', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (7, '0101000020E6100000B81E85EB51185D404C37894160F54340', '2008 Summer Olympics & 2022 Winter Olympics', 'Beijing', 'China', '2');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (29, '0101000020E6100000A01A2FDD249645C0D578E92631E836C0', '2016 Summer Olympics', 'Rio de Janeiro', 'Brazil', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (10, '0101000020E61000007B14AE47E17A1B40A01A2FDD24F64640', '1924 Winter Olympics', 'Chamonix', 'France', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (38, '0101000020E6100000D122DBF97EAA23400000000000404740', '1928 & 1948 Winter Olympics', 'St. Moritz', 'Switzerland', '2');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (16, '0101000020E6100000D7A3703D0A7F52C0F853E3A59B244640', '1932 & 1980 Winter Olympics', 'Lake Placid', 'United States', '2');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (12, '0101000020E6100000CDCCCCCCCC4C26400000000000C04740', '1936 Winter Olympics', 'Garmisch-Partenkirchen', 'Germany', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (26, '0101000020E610000000000000008025409A99999999F94D40', '1952 Winter Olympics', 'Oslo', 'Norway', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (11, '0101000020E61000006ABC7493184428404E62105839444740', '1956 Winter Olympics', 'Cortina', 'Italy', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (36, '0101000020E6100000D7A3703D0A0F5EC00C022B8716994340', '1960 Winter Olympics', 'Squaw Valley', 'United States', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (15, '0101000020E61000006ABC749318C426401904560E2DA24740', '1964 & 1976 Winter Olympics', 'Innsbruck', 'Austria', '2');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (13, '0101000020E610000017D9CEF753E316409A99999999994640', '1968 Winter Olympics', 'Grenoble', 'France', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (32, '0101000020E61000003333333333AB61407F6ABC7493884540', '1972 Winter Olympics', 'Sapporo', 'Japan', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (33, '0101000020E6100000986E1283C06A3240E5D022DBF9EE4540', '1984 Winter Olympics', 'Sarajevo', 'Yugoslavia', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (9, '0101000020E6100000068195438B845CC083C0CAA145864940', '1988 Winter Olympics', 'Calgary', 'Canada', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (1, '0101000020E6100000DF4F8D976E921940105839B4C8D64640', '1992 Winter Olympics', 'Albertville', 'France', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (17, '0101000020E610000004560E2DB2DD2440713D0AD7A3904E40', '1994 Winter Olympics', 'Lillehammer', 'Norway', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (25, '0101000020E610000033333333334361400000000000204240', '1998 Winter Olympics', 'Nagano', 'Japan', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (31, '0101000020E6100000B81E85EB51F85BC00000000000604440', '2002 Winter Olympics', 'Salt Lake City', 'United States', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (42, '0101000020E6100000CDCCCCCCCCCC1E407F6ABC7493884640', '2006 Winter Olympics', 'Turin', 'Italy', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (43, '0101000020E610000039B4C876BEC75EC04E62105839A44840', '2010 Winter Olympics', 'Vancouver', 'Canada', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (35, '0101000020E61000005C8FC2F528DC43407B14AE47E1CA4540', '2014 Winter Olympics', 'Sochi', 'Russia', '1');
INSERT INTO public.olympic_cities (id, geom, year, city, country, times_hosted) VALUES (28, '0101000020E6100000CDCCCCCCCC0C6040E5D022DBF9AE4240', '2018 Winter Olympics', 'Pyeongchang', 'South Korea', '1');
